global:
  scrape_interval: 15s  # Intervalo global de recolecci贸n de datos
  evaluation_interval: 15s  # Intervalo global para evaluar reglas

scrape_configs:
  - job_name: "mysql-exporter"
    static_configs:
      - targets: 
          - "192.168.0.94:9104"  # Direcci贸n y puerto del MySQL Exporter

  - job_name: "prometheus"
    static_configs:
      - targets: 
          - "192.168.0.90:9090"  # Direcci贸n y puerto del propio Prometheus

  - job_name: "cadvisor"
    static_configs:
      - targets: 
          - "192.168.0.81:8080"  # Direcci贸n y puerto del propio Prometheus
